### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by mirh** [KarlitosVII/trilogy-save-editor#1]
I have a 1440p monitor (and god forbid those poor souls with a 4K one), and I'm killing my eyes trying to read the little text.

**Comment by KarlitosVII** [comment]
HiDPI is supported by default.
I have a 1080p screen so I'm not very familiar with higher resolution.
Is it only the text that is small or other part of the software?
Can you share a screenshot ?

**Comment by mirh** [comment]
![immagine](https://user-images.githubusercontent.com/9366725/116626335-55ad6380-a94b-11eb-95ec-db847853f249.png)

**Comment by KarlitosVII** [comment]
New version should works now

**Comment by mirh** [comment]
Besides perhaps the first tab, the font seems bigger. 
Unfortunately it's like stretched out rather than rendered at a higher resolution. 

And for some reason, now if I try to open v1.0 font is like a bunch of times smaller.

**Comment by mirh** [comment]
I suppose this is as good as you can get for the moment..
https://github.com/ocornut/imgui/pull/2826

**Comment by mirh** [comment]
2.0 is [smooth](5) and sexy, thanks. 
I think you should still offer a "portable" zip release though.

**Comment by KarlitosVII** [comment]
Thanks. :)
I added a setup because it installs the WebView2 runtime if needed and because 90% of the reported issues come from people who did not extract the archive correctly.
I agree that I could add a portable version but the auto updater currently need a setup. I'm not sure how to manage auto update in that case.

**Comment by mirh** [comment]
Duh, yet another browser-based app.. and it's kinda strange to need 100MB of dependencies only for a small utility. 
But whatever can make up development good for you I guess? At least W7 is still up and running.

**Comment by KarlitosVII** [comment]
This is not a problem because it shares the same binaries as Edge, which is already installed on most Windows and will be integrated by default in Windows 11.
