### ISSUE TITLE
ME1 Autosave won't load (Linux)

### ISSUE THREAD

**Issue by ensiform** [KarlitosVII/trilogy-save-editor#10]
`Unexpected end of file, some data in your save are unexpected or your save is corrupted ?
Save again and retry. If this error persists, please report bug with save attached`

[Kate00_AutoSave.pcsav.zip](https://github.com/KarlitosVII/trilogy-save-editor/files/6527165/Kate00_AutoSave.pcsav.zip)

**Comment by KarlitosVII** [comment]
It load just fine for me did you download the latest version.

**Comment by ensiform** [comment]
I compiled from source on Linux

**Comment by KarlitosVII** [comment]
I compiled it in wsl and it work just fine with the latest commit.

**Comment by ensiform** [comment]
I just recompiled with release and made sure the plot files are up to date and its definitely still broken for me.

[Kate00.zip](https://github.com/KarlitosVII/trilogy-save-editor/files/6529017/Kate00.zip)

_08 loads, _09 and the autosave do not.

**Comment by KarlitosVII** [comment]
I have really no idea. I tested all 4 of your saves on Ubuntu 20.04 with latest Rust (1.52.1) and I cannot reproduce your bug. :/

**Comment by mirh** [comment]
Send each other your executables, and see if it's a runtime or compilation problem.

**Comment by ensiform** [comment]
My rustc is `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

[trilogy_save_editor.zip](https://github.com/KarlitosVII/trilogy-save-editor/files/6533597/trilogy_save_editor.zip)

**Comment by DistantThunder** [comment]
Using Linux (Arch) Compiled the latest from main branch, opened the AutoSave provided in this thread and it works on my end.

`rustc 1.52.1` as well.

**Comment by ensiform** [comment]
Suddenly it loads and have done nothing different... :thinking:
