### ISSUE TITLE
ME1 Changes - Achievements?

### ISSUE THREAD

**Issue by Dorzalty** [KarlitosVII/trilogy-save-editor#11]
Hey,

I'm wondering if the changes we can make to ME1, in particular, can help activate achievements? For example, romancing someone? I forgot to romance someone in ME1, if I edited my save, saved it and reloaded it in the game, would it activate the achievement for me? I just beat the game, so I really don't want to go back just for 1 achievement. lol

**Comment by mirh** [comment]
https://github.com/KarlitosVII/trilogy-save-editor/issues/2

**Comment by Dorzalty** [comment]
Is that where that stuff is stored? If so, I'm sorry, I didn't know. I thought it was a save editor thingy or possible through it, my bad.

**Comment by mirh** [comment]
Saves and the global profile are different.

**Comment by Dorzalty** [comment]
Okay, I didn't know that when I made the thread.

**Comment by KarlitosVII** [comment]
Most achievements are triggered at a specific time. For example, you have to use a save just before Ilos if you want to earn the romance achievement. For "numbers" achievement like use a power 25 times, they are stored in profiles.
