### ISSUE TITLE
ME1 Plot Bool Variables without names

### ISSUE THREAD

**Issue by marianomdq** [KarlitosVII/trilogy-save-editor#12]
Hello!

Is there a possibility to have names for what each Bool, Int and Float variable mean?

P.S: Excellent work btw

**Comment by KarlitosVII** [comment]
Curious question.
That's what the "Plot" tab is for.

**Comment by marianomdq** [comment]
Here's my scenario. This triggered my question:

I forgot to do the `[Feros] Retrieve Gavin's Data` mission. So, I went to the saves editor and checked that mission as completed. The issue is that the mission remained active in the "Secondary Quests" panel the whole game. I believe it was because I didn't have the OSD in the "inventory" and thus, I was unable to speak with Gavin about this mission, maybe triggering the event that would clean that mission from the secondary missions panel.

Seeing that there a lot more items in the Raw tab than there are in the Plot tab, maybe by knowing what each of those represent I'd be able to "give" myself the OSD.

**Comment by KarlitosVII** [comment]
This is a Journal/Codex issue. Unfortunately, I have not yet reverse engineered the entire save and these values are not available.

**Comment by mirh** [comment]
WELL WELL WELL
https://github.com/electronicarts/MELE_ModdingSupport

**Comment by KarlitosVII** [comment]
I am pooping in my pants. I worked 10h on TSE today but I think I won't sleep tonight. xD

**Comment by mirh** [comment]
Just make sure to also cross-check the original games, once you feel like it.
