### ISSUE TITLE
Some mission checks in ME1LE are not showing properly

### ISSUE THREAD

**Issue by ruyruin** [KarlitosVII/trilogy-save-editor#13]
I've used the save editor on my most recent save from ME1LE and for example I have done two missions that are already completed in the journal log:

https://masseffect.fandom.com/wiki/Citadel:_The_Fourth_Estate
https://masseffect.fandom.com/wiki/UNC:_Major_Kyle

But the mission checks from those saves aren't showing any check in the editor despite being completed:

![image](https://user-images.githubusercontent.com/79366471/120004188-026c1680-bfc6-11eb-9e11-f61fabbf940f.png)

![image](https://user-images.githubusercontent.com/79366471/120004252-11eb5f80-bfc6-11eb-895f-ce2e572f92ad.png)

**Comment by ruyruin** [comment]
Forgot to say I'm using version 1.7.1

**Comment by KarlitosVII** [comment]
This is a bug in ME1 not TSE.
