### ISSUE TITLE
Feature: Open the save dialog in the save file's directory

### ISSUE THREAD

**Issue by trevorgunn** [KarlitosVII/trilogy-save-editor#14]
Caveat: I'm running this on Linux but I don't believe that changes this particular behaviour.

Problem: when saving, the save dialog opens in the current working directory instead of the directory holding the open save file. It would be more convenient for me if the save dialog were to open in the directory of the open save file.

I think this can be fixed by simply changing

```diff
- file_name: file_name.to_string_lossy().into()
+ file_path: path.to_string_lossy().into()
```

in https://github.com/KarlitosVII/trilogy-save-editor/blob/7ddc41dcccc92e7f532a0a1c0a440d7eb3d17a76/src/event_handler.rs#L79

From my brief search, I can only find the `file_name` field being used in the save dialog, so I don't think this breaks anything.

**Comment by KarlitosVII** [comment]
Good catch, some the code have been written when I used `rfd` instead of `tinyfiledialogs`.
