### ISSUE TITLE
[ME3] Unlocking Reave

### ISSUE THREAD

**Issue by lawliet89** [KarlitosVII/trilogy-save-editor#17]
I missed the conversation with Kaidan and I did not unlock Reave. When using the save editor to enable Reave, it gets disabled from the save file the moment I use the reassign powers "console". Is there any plot points I missed when I edited the save?

I know I can just set the bonus power to Reave manually, but just wanted to ask for "completeness".

**Comment by KarlitosVII** [comment]
Unfortunately, I can't do anything about that. Bonus powers unlocks are stored in game profile not in the saves. You need a save just before the key dialog.

**Comment by lawliet89** [comment]
I see. Thanks for the info!

**Comment by lawliet89** [comment]
I see. Thanks for the info! Any pointers for how the game profile can be edited, if possible?
