### ISSUE TITLE
Display error message if content files are not found

### ISSUE THREAD

**Issue by Juhannuspukki** [KarlitosVII/trilogy-save-editor#19]
After downloading this program I extracted the files to my desktop, then moved the executable to its own folder and spent 30 minutes wondering what is wrong with the program since most of the options I expected to see were missing. Turns out I had not copied all of the required files to this new folder, but the program was still able to run. Instead of failing silently it would be beneficial to display an error message if the required content files are not present.

**Comment by KarlitosVII** [comment]
This is already the case and a lot of people seem to have difficulty extracting the zip properly for some reasons that goes over my head. This is why this error message is the first entry in the [FAQ](https://github.com/KarlitosVII/trilogy-save-editor/wiki/Frequently-Asked-Questions).

**Comment by Juhannuspukki** [comment]
Strange, you are absolutely correct. There is an error message. The first time I used this program the error was not displayed even though the plot files were in the wrong place, but I cannot seem to reproduce the issue anymore. As for extracting the zip, I believe most people do as I do: they right-click drag the file from the downloads folder to the desktop and choose "extract here" which means that any ambiguously named files get lost among all the other crap we have on the desktop. Also thank you for adding the link to the FAQ to the readme.
