### ISSUE TITLE
Program won't start on virtualized Windows

### ISSUE THREAD

**Issue by Juhannuspukki** [KarlitosVII/trilogy-save-editor#20]
When attempting to start this program on Windows 10 running on VMware Fusion, the following terminal window appears for a few fractions of a second after which the program crashes.

<img width="921" alt="Screenshot 2021-06-02 at 8 15 18" src="https://user-images.githubusercontent.com/25532806/120427694-11164d00-c37b-11eb-855d-bfca4c0d535b.png">

**Comment by ProjectSynchro** [comment]
This is also the case when running this on bare metal, it appears the refreshrate of my display is changing, or the display driver is crashing.

**Comment by KarlitosVII** [comment]
Can you tell me if it works for you in 1.9.0 with fallback and backend args?

**Comment by ProjectSynchro** [comment]
> 
> 
> Can you tell me if it works for you in 1.9.0 with fallback and backend args?

Testing 1.9.0 with all three backends (dx11, dx12, and vulkan) does not reproduce the crashes seen in 1.8.3.

**Comment by KarlitosVII** [comment]
Weird, Vulkan is the default and I did not change anything.

**Comment by mirh** [comment]
Maybe this could be fixed with https://github.com/ocornut/imgui/pull/2724

**Comment by KarlitosVII** [comment]
With the new version, many things have changed. Please try v2.0.0 and feel free to open another issue if you wish. :)
