### ISSUE TITLE
Appearance options missing in 1.10.0

### ISSUE THREAD

**Issue by The-Terraformer** [KarlitosVII/trilogy-save-editor#22]
Under ME3 - Appearances - Full Body
We appear to be missing the Shade, Spirit and Nightmare options.
They were there in previous versions.
Thank you.

**Comment by The-Terraformer** [comment]
Update. They appear once you get onboard the Normandy. I'm guessing they are only available once a certain trigger is passed.

**Comment by mirh** [comment]
Maybe a tooltip could be added to mention this.
