### ISSUE TITLE
Ps4 save Support

### ISSUE THREAD

**Issue by SkillerCMP** [KarlitosVII/trilogy-save-editor#24]
Could you Add support to Load in .ps4sav files (Me2/3 since they are not encrypted can be loaded)
Me1 format from SW has the Encryption layer taken off but the format under is the exact same If you have the ability to Skip the ME1 Crypt when it sees a .ps4save file could import, and then on Save Skip Me1 encryption again 

Great Program.
hope it helps .. Save
[Jane00_01.zip](https://github.com/KarlitosVII/trilogy-save-editor/files/6689895/Jane00_01.zip)

**Comment by KarlitosVII** [comment]
It works just fine with my ME1LE template. This will be an easy fix. Thank you.
Can you confirm that the PS4 saves for ME2/3 are exactly the same as those for PC ?

**Comment by SkillerCMP** [comment]
they are only change is the .ps4sav ending compared to pcsave

**Comment by KarlitosVII** [comment]
Fixed in 1.13.0. :)
