### ISSUE TITLE
Having a problem launching editor

### ISSUE THREAD

**Issue by Dano25655** [KarlitosVII/trilogy-save-editor#25]
Just downloaded the editor, when i try launching it gives me this then crashes
![Shit Dude](https://user-images.githubusercontent.com/86291420/122896346-d65e5f80-d2fd-11eb-8e2d-ae021ac76004.png)

**Comment by mirh** [comment]
Duplicate of #20

**Comment by KarlitosVII** [comment]
Does using directly --dx11 or --dx12 works ?

**Comment by Dano25655** [comment]
No it does not
