### ISSUE TITLE
Black screen on start

### ISSUE THREAD

**Issue by Skzenku** [KarlitosVII/trilogy-save-editor#26]
Hello, I don't know why but I've a black screen with a error message when I start the editor. I've downloaded the required files Visual C++ and I tried to start with the cmd command but still nothing...

![TSE error](https://user-images.githubusercontent.com/22574870/123113326-c1d5b080-d43e-11eb-9e20-3e998a4671ab.jpg)

**Comment by mirh** [comment]
Sigh, can't y'all people check other issues first?  #25

**Comment by Skzenku** [comment]
I've already checked that issues.

**Comment by mirh** [comment]
And are you using the latest version from here? That folder doesn't sound like a github download.

**Comment by Skzenku** [comment]
Yes, the latest found on Nexusmods.

**Comment by Skzenku** [comment]
I'm on windows 7. That can be the issue ?

**Comment by Skzenku** [comment]
So, I was right. The editor work great on windows 10 and not on windows 7 for me.
