### ISSUE TITLE
Export ME2LE save for importing in old ME3.

### ISSUE THREAD

**Issue by NakedValue** [KarlitosVII/trilogy-save-editor#27]
Could add an option to export an ME2 LE save in the ME 2 format, so that it could be imported in the old ME3. 

As I see it, the only difference between the 2 formats is "me1_import_rewards: Me1ImportRewards," and the save version number. 
I was able to get an ME2 Le save to import into old ME3 by just skip serializing that Me1ImportRewards stuff and changing the version number.

Best regards.

**Comment by KarlitosVII** [comment]
This is indeed the case but, even better you can import your ME2LE save into ME3LE and use this very save in ME3OT.

**Comment by NakedValue** [comment]
Ok. I have not tried this. Then consider my request useless. :) btw you write really clean code.

**Comment by KarlitosVII** [comment]
Thanks, I do my best to avoid swimming in a mess. ^^

**Comment by mirh** [comment]
Maybe you could have a FAQ entry (or a totally different wiki page?) detailing what changes and backward or forward incompatibilities thgere are there between OG and LE?
