### ISSUE TITLE
Major Kyle issue on version 1.13

### ISSUE THREAD

**Issue by Majedshakir** [KarlitosVII/trilogy-save-editor#28]
In release version 1.13 the Major Kyle quest line is flipped. The surrendered is fought and the fought is surrendered. I have tested both were I got the news in the elevator to confirm.

**Comment by KarlitosVII** [comment]
I'm aware of that. But nothing that requires a full update of TSE. I will update it in the next update, some day.

**Comment by KarlitosVII** [comment]
Fixed
