### ISSUE TITLE
Maxed Out Renegade Bar Through Editor; Intimidate Points Bar Won't Increase Anymore

### ISSUE THREAD

**Issue by Pasdeseul** [KarlitosVII/trilogy-save-editor#29]
Title says it all. Increased the Renegade score to 400, and now the Intimidate bar won't increase any further. I've changed the value to be much higher, lower then higher again, etc. Nothing is working. How do I fix this?

**Comment by mirh** [comment]
But in which game?
ME1 had paragon and renegade be like separate axis
While ME2 had the in-game bar show a proportion of all the points you got.

**Comment by Pasdeseul** [comment]
Apologies for not being very specific. It was early in the morning when I wrote that and I was very tired. 

I'm talking about Mass Effect 1, the persuasion options, specifically the Intimidate skill. You're able to put more points into it as you raise your renegade score. I used the game editor to raise my renegade score to max (or a number that will max it out on the character UI screen), and the intimidate skill bar hasn't gained any new slots to put points into, therefore leaving some speech options unavailable that should have been available at this point in the game.

I'm assuming that, since the bar didn't rise organically like it would have had I raised it legitimately, the Intimidate skill bar didn't increase like it should have. I'm looking for a fix that either increases the available point slots for the Intimidate skill or otherwise allows me to make my Renegade speech checks. Any help that can be offered would be much appreciated.

**Comment by mirh** [comment]
It would be cool if you could confront yourself two saves, where the only differing thing is the number of possible intimidate skill bar points. 
Anyway, I would guess it's something inside m_aSimpleTalents or m_aComplexTalents raw data for m_player?

**Comment by KarlitosVII** [comment]
You have to increase your charm / intimidate talent manually.

https://github.com/KarlitosVII/trilogy-save-editor/wiki/Frequently-Asked-Questions#when-i-add-some-paragon--renegade-points-in-me1-my-charm--intimidate-skill-is-not-increased

**Comment by mirh** [comment]
Looking forward to having all entries "properly labelled" one day 😎

**Comment by Pasdeseul** [comment]
Thank you both KarlitosVII AND mirj for your help. Also thank you KarlitosVII for making the editor in the first place. Much appreciated.
