### ISSUE TITLE
Open File Dialog (Linux?)

### ISSUE THREAD

**Issue by ensiform** [KarlitosVII/trilogy-save-editor#31]
By default the Filter "Mass Effect Trilogy Save" string doesn't show any save files until I remove the filter.

![Screenshot_20210629_201933](https://user-images.githubusercontent.com/997399/123887936-06b68700-d918-11eb-8935-5d73e3eeb6ca.png)
![Screenshot_20210629_202008](https://user-images.githubusercontent.com/997399/123887938-06b68700-d918-11eb-872f-f90a478527ea.png)

**Comment by KarlitosVII** [comment]
As you can see here: https://github.com/KarlitosVII/trilogy-save-editor/blob/190edb54dfc351127cc6521aab0cdfef39f6c41a/src/gui/mod.rs#L271-L278
There is a list of filters and and a label with filters in parenthesis.
`tinyfiledialog` support applescript, zenity, matedialog, qarma, kdialog, Xdialog,
  python2/tkinter and dialog for unix. All with the same API, so this is pretty weird.

**Comment by ensiform** [comment]
For what it's worth there's a blank space after `Save` in the filter box. Not sure if that matters like if it's cutting off from the ( on that line above

**Comment by KarlitosVII** [comment]
With the new version, many things have changed. Please try v2.* and feel free to open another issue if you wish. :)
