### ISSUE TITLE
After opening a save file of mass effect 3, the content of the plot tab is empty.

### ISSUE THREAD

**Issue by otakutyrant** [KarlitosVII/trilogy-save-editor#32]
Is it because it is too difficult to edit the plot of mass effect?

![image](https://user-images.githubusercontent.com/64188229/127770210-1646a0b4-8e0d-442f-bb55-c166516ae211.png)

**Comment by Gibbs1979** [comment]
@otakutyrant You're missing the database files. Don't just double click and run from the zip file. 

I bet you're also getting a database error on startup. 

Make sure you extract all the files onto your desktop or into a folder, then relaunch Trilogy.

![image](https://user-images.githubusercontent.com/7484829/127920874-023028f8-44ad-4cd9-84eb-ae36764cece8.png)

**Comment by KarlitosVII** [comment]
With the new version, many things have changed. Please try v2.0.0 and feel free to open another issue if you wish. :)
