### ISSUE TITLE
vcruntime140_1.dll error

### ISSUE THREAD

**Issue by Djasir** [KarlitosVII/trilogy-save-editor#34]
Editor (1.13.1) doesn't run. Downloaded here.

Error: The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem.

vcredist 2010, 2013, 2015, 2019 installed. Both x86 & x64 versions

**Comment by KarlitosVII** [comment]
With the new version, many things have changed. Please try v2.0.0 and feel free to open another issue if you wish. :)

**Comment by ell1e** [comment]
I am still getting this with 2.2.1 on Windows 10.

**Comment by TheSho21** [comment]
Hello, I found a fix for this. Follow the instructions in this YT video
https://www.youtube.com/watch?v=nEU9qCA9EBA
