### ISSUE TITLE
Raw plot data format in file explanation

### ISSUE THREAD

**Issue by fisheye36** [KarlitosVII/trilogy-save-editor#35]
Hi @KarlitosVII :)

I've just bought ME Legendary Edition and wanted to play ME2 and ME3, having previously played ME1. The problem is that it is impossible to import original ME1 saves into ME2 but I've managed to open my original ME1 save in TSE, as well as some arbitrary LE ME1 save downloaded from the Internet.

Now, I wanted to modify the arbitrary save so that it contains the same choices I made while playing ME1 and I wanted to copy raw plot data. The problem is that there are thousands of Booleans, so I wanted to write a script that will copy values from my save into LE save.

Unfortunately I don't know Rust and it's hard for me to reverse-engineer how to read and write those values from the binary save file itself. Could you point me to a website/document that explains the structure of the save files or do it yourself?

GitHub doesn't support writing direct messages between users and I see that you have chosen to hide your e-mail address, so creating this issue was the only possibility to ask that :)

If that is okay with you, you can use my e-mail address to respond, or add me on [LinkedIn](https://www.linkedin.com/in/kwarchol/).

**Comment by KarlitosVII** [comment]
Hello,
The easiest you can do is importing your ME1OT save to ME2OT then use this very save in ME2LE.
You can also download an ending ME1LE save and edit your save in the `Plot` tab to your liking then import it to ME2. The vast majority of plot used by ME2 are here. You can also edit the `Plot > ME1 Imported` tab after your first save (when you wake up).

If you really want to copy / paste all the plots it's technically possible and relatively easy if you know how to deserialize the save.
Bioware shared the file structure [here](https://github.com/electronicarts/MELE_ModdingSupport/blob/master/DataFormats/ME1_Savegame.h#L53).

**Comment by mirh** [comment]
ME2 imports your `Char_01-********.MassEffectSave` end game files, not the usual save states.
