### ISSUE TITLE
High Booleans, Floats and Integers freeze Trilogy Save Editor

### ISSUE THREAD

**Issue by Herobrine24** [KarlitosVII/trilogy-save-editor#36]
When a save has a high Boolean, Float or Integer count due to mods, the Trilogy Save Editor freezes trying to load any of them, probably because the game writes empty booleans, floats and integers up to the ones that are actually added by a mod and the editor struggles to load all of them.
The highest number supported by the modding toolset is 9 digits long so that should be the maximum that the editor should support.

Example Save:
[John00_07.zip](https://github.com/KarlitosVII/trilogy-save-editor/files/7492183/John00_07.zip)

**Comment by KarlitosVII** [comment]
Thank you for pointing this out to me. I've added a hard cap of `10 000 000`. This is the higher I can do to avoid a capacity overflow panic.
