### ISSUE TITLE
Save as ME2 functionality

### ISSUE THREAD

**Issue by davidwlhf** [KarlitosVII/trilogy-save-editor#38]
Apparently there is a way to import an LE2 save into ME3 (OT).  I do not know the flags that need to be flipped but I know some people already do this.  Would you consider adding "Save as ME2" functionality for LE2 saves for people who want to play the game in LE1 -> LE2 -> ME3(OT) order?  I'm guessing the hard work of noting the flag differences between the saves has already been done.  With no multiplayer assets in LE we may never see a full Miranda mod or a full EGM additional squadmate implementation for LE3.  Thanks for your consideration.

**Comment by mirh** [comment]
Last time I checked they simply didn't do anything. 
All file formats should be unchanged, except those in ME1.

**Comment by davidwlhf** [comment]
Is there a way to make an LE2 save look like an ME2 save?  Like a version field that can be changed?

**Comment by mirh** [comment]
Can't you open the LE2 save in ME2?

**Comment by davidwlhf** [comment]
No just the presence of the save file causes ME2 to crash.  LE2 save file directories look like this: 
 Abby_12_Vanguard_020122_366384c whereas the ME2 version would look like this:  Abby_12_Vanguard_020122   So even if you correct the directory name to the proper ME2 formatting the game crashes before getting to the main menu.  Replace the save file with an actual ME2 save and no crash.  There's something in the LE2 saves that crashes ME2.

**Comment by KarlitosVII** [comment]
If you just want to import your LE2 save into ME3 you just have to import it to LE3 then use this very save into ME3 because there is no difference between ME3/LE3 saves

**Comment by KarlitosVII** [comment]
> Last time I checked they simply didn't do anything. All file formats should be unchanged, except those in ME1.

Only ME3 saves didn't changed. A LE2 save can't be used in ME2 without downgrade it to a lower version.

**Comment by mirh** [comment]
My bad, I must have mixed something with the fact that you can do ME2->LE2.
