### ISSUE TITLE
360 save games support?

### ISSUE THREAD

**Issue by mirh** [KarlitosVII/trilogy-save-editor#4]
Here are [two samples](https://github.com/KarlitosVII/trilogy-save-editor/files/6401988/Saves.zip) (courtesy by The Tech Game). 
Of course I understand if this is too much of a work, though if you could at least get them to convert to pc format.. I always liked the [idea](https://eplight.org/me2/) of *making people ascend*, if I can explain.

**Comment by KarlitosVII** [comment]
I doesn't support Xbox 360 because saves are big endian and this is too much work to support this when I don't know how many people will use it and considering Legendary release in 2 weeks.
Gibbed's fork support it if you really want it.

**Comment by mirh** [comment]
AFAIK save transfer is only possible/tested/documented with ME2 specifically. 
Anyhow, got it.

**Comment by mirh** [comment]
Very fun fact
LE2 and LE3 save games should be compatible with their respective older games. 
LE1 is [said](https://arstechnica.com/gaming/2021/05/mass-effect-legendary-edition-tests-thoughts-and-a-10-am-edt-twitch-stream/2/) to have its save game format upgraded. 

So.. I guess like it's all a whole big circus

**Comment by KarlitosVII** [comment]
Yes and no.
ME2 is version 30 instead of 29 so and I needed to update it.
ME3 is exactly the same.
ME1 have the same file extension but the format seems to be UAsset so it seems I will need to dig in unreal engine code...
