### ISSUE TITLE
Add Achievement

### ISSUE THREAD

**Issue by Good-Viper** [KarlitosVII/trilogy-save-editor#46]
Is it possible to add/give yourself an achievement in ME1, ME2 or ME3 in the "Trilogy Save Editor"?
If not, can you add this feature?

**Comment by mirh** [comment]
That would require decoding of Profile.MassEffectProfile (#2), Player1.prf and local_profile.sav.

**Comment by mirh** [comment]
https://github.com/ME3Tweaks/ME1-ASI-Plugins/blob/master/ME1-SDK/SDK/ME1_BIOC_Base_structs.hpp#L4445
https://github.com/ME3Tweaks/ME2-ASI-Plugins/blob/master/ME2-SDK/SDK_HEADERS/SFXGame_structs.h#L1762
http://me3explorer.freeforums.org/me3-profile-editor-t1395.html
https://github.com/PrivateServerEmulator/ME3PSE/blob/master/ME3Server_WV/Local_Profile.cs

**Comment by levicki** [comment]
Why not just play and get them?

**Comment by mirh** [comment]
I mean, you could ask the same question about the whole remainder of the project...
Truthfully, adding achievement that you never earned seems slightly different from tinkering with the normal inventory or something, but even with this consideration there is still plenty of fair usage. For instance, I personally lost my Player1.prf after a playthrough, and getting everything back again normally pisses me off a bit. 

And then there's some variables that just aren't in masseffectsaves/pcsavs. 
In ME2 and ME3 I could tell you about the login details (which maybe could solve the problems with authentication of the former). In ME1.. I don't know, there is volume at least? And then different controller sensitivities perhaps.

**Comment by mirh** [comment]
https://github.com/ME3Tweaks/LegendaryExplorer/tree/Beta/LegendaryExplorer/LegendaryExplorerCore/Save
Not sure how much this could apply to the original games (2 and 3 maybe, unlikely for 1) but there's development happening in this regard
