### ISSUE TITLE
"accepted spectre reinstatement" flag broken

### ISSUE THREAD

**Issue by swordclash117** [KarlitosVII/trilogy-save-editor#6]
Checking this flag doesn't actually do anything. Either this flag was somehow broken when implementing it in the save editor or another flag somewhere was missed that needs to be activated at the same time as the supposedly faulty flag in order for Shepard's spectre status to get upheld and not "reinstated", perhaps a flag somewhere that says that the "Citadel: The Council" mission was complete. Or it could be an integer, who knows.

I've checked all the flags that say I played ME1 and ME2 and that the save was "imported" from ME2, in addition to the flags that say Anderson was chosen as the councilor, and the council was saved. This issue is not new, I've also encountered it in Gibbed's ME3 save editor (both the original and the various forks), and I've done extensive testing on both the PC and Xbox 360 version of ME3, using different combos of relevant flags on or off, to confirm this issue.

It's strange because when you actually import a file from ME2 where spectre reinstatement was accepted, Shepard's spectre status is upheld but when you try to simulate having "imported" a ME2 file using the trilogy save editor (in additon to Gibbed's save editors) with the same plot point as above, this flag for some reason is broken

**Comment by KarlitosVII** [comment]
The majority of plots I use are from Gibbed's, forks and ME3Explorer plot db. I didn't test everything, so if some plots didn't work in the past they will not work in TSE, unfortunately. Most of my research is about saves reverse engineering and for now I have limited knowledge about finding and debugging plots.

**Comment by mirh** [comment]
Showerthought: can't you see which flag is set when and where in ME3explorer?

**Comment by swordclash117** [comment]
after using a newer and updated fork of ME3 explorer to look at the plot db, I can see that the "accepted spectre reinstatement" is a boolean. However I see no way to manually set a bool in the trilogy save editor, but there is a way to do so in Gibbed's save editor.

**Comment by KarlitosVII** [comment]
You can edit arbitrary plot in Raw > plot. But if you look into plot/ME2KnowPlot.ron I already use this plot id which is 2169.
