### ISSUE TITLE
add a new tab "GAW Assets ME3 Compatible"

### ISSUE THREAD

**Issue by Yggge** [KarlitosVII/trilogy-save-editor#9]
add a new tab "GAW Assets ME3 Compatible"
add a new plot in Me1KnownPlot.ron

        "GAW Accets ME3 Compatible": PlotCategory(
            booleans: {
                2883: "Retrieved Gavin's data",
                3141: "[The Fan] Met Conrad Verner",
                3142: "[The Fan] Charmed him",
                3899: "[Rita's Sister] Completed assignment",
                5386: "[Scan the Keepers] Accepted quest",
                7164: "Got Elkoss Combine license",
            },
            ints: {
                39: "Citadel: Keepers scanned (0-21)",
                43: "League Medallions (0-10 max 12)",
                48: "Light Metals (0-20 max 34)",
                50: "Heavy Metals (0-20 max34)",
                51: "Gases (0-6 max 10)",
                52: "Rare Earths (0-20 max 36)",
                53: "Prothean Artifact (0-7 max 10)",
                54: "Asari Writings(0-10 max 16)",
                55: "Turian Emblem (0-13 max 17)",
                56: "Salarian ID Tags (0-3 max 4)",
            },
        ),
![GAW Assets ME3 Compatible](https://user-images.githubusercontent.com/36107183/118610763-71e04a00-b7ff-11eb-841f-a9a7d6339901.png)

**Comment by KarlitosVII** [comment]
Thank you !
I'm not sure if I will duplicate theses plots in a "GAW Assets"-like category but I will add it in the plot table.
